#include "baseSimulator.h"
#include "baseSimulator.hh"

#include "gtest/gtest.h"

// #include "abstract/Architecture.test.cpp"
// #include "abstract/BigDroplet.test.cpp"
// #include "abstract/Continuous.test.cpp"
// #include "abstract/GradientGenerator.test.cpp"
// #include "abstract/InstantaneousMixing.test.cpp"
// #include "abstract/Tank.test.cpp"
// #include "abstract/Topology.test.cpp"
// #include "hybrid/Hybrid.test.cpp"
// #include "hybrid/Opening.test.cpp"
#include "cfd/Cfd.test.cpp"
