#include "simulation/CFDSim.h"
#include "simulation/Fluid.h"
#include "simulation/MixingModels.h"
#include "simulation/Mixture.h"
#include "simulation/ResistanceModels.h"
#include "simulation/Simulation.h"

#include "nodalAnalysis/NodalAnalysis.h"

#include "architecture/Channel.h"
#include "architecture/Edge.h"
#include "architecture/FlowRatePump.h"
#include "architecture/modules/Module.h"
#include "architecture/modules/CFDModule.h"
#include "architecture/modules/ContinuousModule.h"
#include "architecture/modules/OrganModule.h"
#include "architecture/Network.h"
#include "architecture/Node.h"
#include "architecture/Platform.h"
#include "architecture/PressurePump.h"

#include "postProcessors/navierStokesAdvectionDiffusionCouplingPostProcessor2D.h"
#include "postProcessors/saturatedFluxPostProcessor2D.h"
#include "postProcessors/setFunctionalRegularizedHeatFlux.h"