name: Ubuntu-test

on:
  pull_request:
    types: [opened, reopened, edited]
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Configure CMake
      run: cmake -DTEST=ON -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build

    - name: Test 
      working-directory: ${{github.workspace}}/build
      run: ./simulatorTest